#!/usr/bin/env bash
## Behavioural check on the interactive entry of the agents console: a plain
## `bash DistroAgentsConsole.sh` with no argument, which is exactly what the editor's
## "Start Agents Console" task runs. With SPAWN_CLI_SERVICE naming a harness leg
## (claude, copilot, scaleway) the console runs the existing
## `DistroAgentsTools.fn.sh --intern-root-harness` with no option of its own, and runs
## no vendor binary and no claude-native. The vendor binary starts only when the
## service is selected by name, claude-native / copilot-native, by the setting or
## --cli, and then exports no stored key. A leg chosen any other way (--cli, the PATH
## scan) opens the bash console and says what was chosen, by what, and that nothing was
## started. A spawn (--non-interactive) keeps running the harness leg. Each refusal has
## an accepted sibling that differs from it in the one thing the refusal is about.
## The console is generated by --make-console-command into the rig's own workspace,
## then run with no MMDAPP and no MDLT_ORIGIN in the environment, so it resolves them
## from its own path and the workspace's settings as a real entry does, and reads
## SPAWN_CLI_SERVICE through the real config reader. The origin it resolves is a rig
## copy of the real tree (symlinks) whose DistroAgentsTools.fn.sh is a stub: it logs a
## call of --intern-root-harness and hands every other operation to the real one, so no
## Slack and no spawn happens. RIG_CONSOLE may name another console file to judge
## instead, for a red run. Every run goes through one `env -i` whose child refuses to
## start outside the rig tree, and a CLI named claude or copilot in its PATH is a stub
## or the run is refused: the real binary is never started.
set -u
: "${MDLT_ORIGIN:?⛔ ERROR: MDLT_ORIGIN is not set}"
rigFn="$MDLT_ORIGIN/myx/myx.distro-agents/sh-scripts/DistroAgentsTools.fn.sh"

rigRefuse(){
	echo "⛔ ERROR: $1 -- refusing to report a result" >&2 ; exit 1
}
[ -x "$rigFn" ] || rigRefuse "dispatcher not found: $rigFn"
rigTmp="$( mktemp -d -t AgentsConsoleInteractiveEntryCheck )" || exit 1
rigTmp="$( cd "$rigTmp" && pwd -P )" || exit 1
trap 'rm -rf -- "$rigTmp"' EXIT

rigPassCount=0
rigFailCount=0
rigAssert(){ ## what is asserted, got, want
	if [ "$2" = "$3" ] ; then
		printf '  PASS  %s\n' "$1" ; rigPassCount=$(( rigPassCount + 1 ))
	else
		printf '  FAIL  %s\n        got:  %s\n        want: %s\n' "$1" "$2" "$3" ; rigFailCount=$(( rigFailCount + 1 ))
	fi
}

## One console, generated once from the template by the real generator.
rigGen="$rigTmp/gen"
mkdir -p "$rigGen/ws/.local/.agents" "$rigGen/home" "$rigGen/bin"
printf 'MDLT_CONSOLE_ORIGIN=%s\n' "$MDLT_ORIGIN" > "$rigGen/ws/.local/MDLT.settings.env"
if [ -n "${RIG_CONSOLE:-}" ] ; then
	cp "$RIG_CONSOLE" "$rigGen/ws/DistroAgentsConsole.sh" || rigRefuse "could not copy the console to judge: $RIG_CONSOLE"
else
	env -i HOME="$rigGen/home" PATH="$rigGen/bin:/usr/bin:/bin" MMDAPP="$rigGen/ws" MDLT_ORIGIN="$MDLT_ORIGIN" MDLT_OPTION="--run-from-path $MDLT_ORIGIN" RIG_TMP="$rigTmp" \
		bash -c 'case "$MMDAPP" in "$RIG_TMP"/*) ;; *) echo "RIG-GUARD: MMDAPP outside the rig tree" >&2 ; exit 99 ;; esac ; cd "$MMDAPP" && exec bash "$0" --make-console-command --quiet' "$rigFn" \
		> /dev/null 2> "$rigGen/make.err"
fi
[ -f "$rigGen/ws/DistroAgentsConsole.sh" ] || rigRefuse "no console was generated: $( tail -2 "$rigGen/make.err" 2>/dev/null )"

## The rig origin: every package of the real tree by symlink, and the agents package by
## symlink too except its dispatcher, which is the stub.
rigOrigin="$rigTmp/origin"
mkdir -p "$rigOrigin/myx/myx.distro-agents/sh-scripts"
for rigPkg in "$MDLT_ORIGIN"/myx/* ; do
	[ "${rigPkg##*/}" != "myx.distro-agents" ] || continue
	ln -s "$rigPkg" "$rigOrigin/myx/${rigPkg##*/}"
done
for rigPkg in "$MDLT_ORIGIN"/myx/myx.distro-agents/* ; do
	[ "${rigPkg##*/}" != "sh-scripts" ] || continue
	ln -s "$rigPkg" "$rigOrigin/myx/myx.distro-agents/${rigPkg##*/}"
done
for rigPkg in "$MDLT_ORIGIN"/myx/myx.distro-agents/sh-scripts/* ; do
	[ "${rigPkg##*/}" != "DistroAgentsTools.fn.sh" ] || continue
	ln -s "$rigPkg" "$rigOrigin/myx/myx.distro-agents/sh-scripts/${rigPkg##*/}"
done
printf '#!/bin/sh\ncase "$1" in\n\t--intern-root-harness) printf "called %%s\\n" "$*" >> "$MMDAPP/../root.log" ; printf "workspace %%s\\n" "$MMDAPP" >> "$MMDAPP/../root.log" ; exit 0 ;;\nesac\nexec "%s" "$@"\n' "$rigFn" \
	> "$rigOrigin/myx/myx.distro-agents/sh-scripts/DistroAgentsTools.fn.sh"
chmod +x "$rigOrigin/myx/myx.distro-agents/sh-scripts/DistroAgentsTools.fn.sh"

## A fresh workspace: the generated console, settings naming the rig origin, a configured
## service (or none) and a stored key, and a stub for each vendor CLI asked for.
rigScenario(){ ## name, SPAWN_CLI_SERVICE or empty, stored key or empty, stub names...
	rigDir="$rigTmp/$1" ; rigService="$2" ; rigKeyStored="$3" ; shift 3
	mkdir -p "$rigDir/ws/.local/.agents" "$rigDir/bin" "$rigDir/home"
	cp "$rigGen/ws/DistroAgentsConsole.sh" "$rigDir/ws/DistroAgentsConsole.sh"
	printf 'MDLT_CONSOLE_ORIGIN=%s\n' "$rigOrigin" > "$rigDir/ws/.local/MDLT.settings.env"
	: > "$rigDir/ws/.local/.agents/magic-team.agent.env"
	[ -z "$rigService" ] || printf 'SPAWN_CLI_SERVICE=%s\n' "$rigService" >> "$rigDir/ws/.local/.agents/magic-team.agent.env"
	[ -z "$rigKeyStored" ] || printf 'ANTHROPIC_API_KEY=%s\n' "$rigKeyStored" >> "$rigDir/ws/.local/.agents/magic-team.agent.env"
	: > "$rigDir/cli.log" ; : > "$rigDir/root.log"
	for rigStub in "$@" ; do
		printf '#!/bin/sh\nif [ "$1" = auth ] ; then echo "{\\"loggedIn\\":true}" ; exit 0 ; fi\nprintf "started %s key=[%%s]\\n" "${ANTHROPIC_API_KEY:-}" >> "%s/cli.log"\n' "$rigStub" "$rigDir" > "$rigDir/bin/$rigStub"
		chmod +x "$rigDir/bin/$rigStub"
	done
}
## One console run, guarded, in the entry form of the editor task: bash <console> <args...>, stdin closed.
rigEntry(){ ## console args...
	env -i HOME="$rigDir/home" PATH="$rigDir/bin:/usr/bin:/bin" RIG_TMP="$rigTmp" RIG_CONSOLE="$rigDir/ws/DistroAgentsConsole.sh" \
		bash -c '
			case "$RIG_CONSOLE" in "$RIG_TMP"/*) ;; *) echo "RIG-GUARD: console outside the rig tree" >&2 ; exit 99 ;; esac
			for rigName in claude copilot ; do
				case "$( command -v "$rigName" )" in ""|"$RIG_TMP"/*) ;; *) echo "RIG-GUARD: $rigName is not a rig stub" >&2 ; exit 99 ;; esac
			done
			[ -z "${MMDAPP:-}" ] && [ -z "${MDLT_ORIGIN:-}" ] || { echo "RIG-GUARD: the entry must start with no MMDAPP and no MDLT_ORIGIN" >&2 ; exit 99 ; }
			exec bash "$RIG_CONSOLE" "$@"
		' rig "$@" < /dev/null > "$rigDir/out" 2> "$rigDir/err"
	printf '%s' "$?" > "$rigDir/rc"
}
rigStarted(){ ## name
	LC_ALL=C grep -c "^started $1 " "$rigDir/cli.log" || :
}
rigKey(){ ## name
	LC_ALL=C sed -n "s/^started $1 key=\[\(.*\)\]\$/\1/p" "$rigDir/cli.log" | head -1
}
rigHolds(){ ## file, text
	LC_ALL=C grep -q -F -- "$2" "$1" && printf yes || printf no
}
rigBashConsole(){ ## the bash console opened: its own line is on stderr
	rigHolds "$rigDir/err" 'AgentsConsole: bash console'
}
rigRootCalls(){ ## how many times the root harness was called
	LC_ALL=C grep -c '^called ' "$rigDir/root.log" || :
}
rigRootCall(){ ## the one call's arguments, exactly
	LC_ALL=C sed -n 's/^called //p' "$rigDir/root.log" | head -1
}
rigNative(){ ## how many lines of what the console printed say claude-native or copilot-native
	LC_ALL=C cat "$rigDir/out" "$rigDir/err" | LC_ALL=C grep -c -e 'claude-native' -e 'copilot-native' || :
}

echo "-- the editor task entry, claude (our harness leg) configured, the command claude in PATH, a key stored --"
rigScenario entry-claude claude rig-key-1 claude
rigEntry
rigAssert "the root harness is called, once"                "$( rigRootCalls )" 1
rigAssert "with its own defaults and no option of ours"     "$( rigRootCall )" "--intern-root-harness"
rigAssert "in this workspace"                               "$( LC_ALL=C sed -n 's/^workspace //p' "$rigDir/root.log" | head -1 )" "$rigDir/ws"
rigAssert "no bash console opens"                           "$( rigBashConsole )" no
rigAssert "no vendor binary is started"                     "$( rigStarted claude )" 0
rigAssert "claude-native appears nowhere in what it prints" "$( rigNative )" 0
echo "-- sibling: the same entry, claude-native selected by name --"
rigScenario entry-native claude-native rig-key-1 claude
rigEntry
rigAssert "the vendor claude is started"                    "$( rigStarted claude )" 1
rigAssert "named claude-native, as selected"                "$( rigHolds "$rigDir/out" 'DISTRO_CONSOLE_EXEC=claude-native' )" yes
rigAssert "the root harness is not called"                  "$( rigRootCalls )" 0
rigAssert "and the stored key is not exported to it"        "$( rigKey claude )" ""

echo "-- the editor task entry, copilot (our harness leg) configured, the command copilot in PATH --"
rigScenario entry-copilot copilot "" copilot
rigEntry
rigAssert "the root harness is called, once"                "$( rigRootCalls )" 1
rigAssert "no vendor binary is started"                     "$( rigStarted copilot )" 0
echo "-- sibling: copilot-native selected by name --"
rigScenario entry-copilot-native copilot-native "" copilot
rigEntry
rigAssert "the vendor copilot is started"                   "$( rigStarted copilot )" 1
rigAssert "the root harness is not called"                  "$( rigRootCalls )" 0

echo "-- the editor task entry, scaleway (a leg with no vendor binary at all) configured --"
rigScenario entry-scaleway scaleway ""
rigEntry
rigAssert "the root harness is called, once"                "$( rigRootCalls )" 1
rigAssert "no bash console opens"                           "$( rigBashConsole )" no

echo "-- refusal: nothing configured, the command claude in PATH (the scan takes the leg; the root harness takes its CLI from the setting) --"
rigScenario scan-claude "" "" claude
rigEntry
rigAssert "the bash console opens"                          "$( rigBashConsole )" yes
rigAssert "the root harness is not called"                  "$( rigRootCalls )" 0
rigAssert "no vendor binary is started"                     "$( rigStarted claude )" 0
rigAssert "it says the PATH scan chose the leg"             "$( rigHolds "$rigDir/err" 'chosen by the PATH scan' )" yes
rigAssert "it says nothing was started"                     "$( rigHolds "$rigDir/err" 'nothing was started' )" yes
rigAssert "it never says claude-native"                     "$( rigNative )" 0
rigAssert "it no longer says no --cli was given"            "$( rigHolds "$rigDir/err" 'no --cli given' )" no
echo "-- sibling of that refusal: the same workspace with SPAWN_CLI_SERVICE=claude (the first entry above) --"
rigAssert "the root harness was called there"               "$( LC_ALL=C grep -c '^called ' "$rigTmp/entry-claude/root.log" || : )" 1

echo "-- refusal: an explicit --cli naming the leg, the setting naming the vendor CLI --"
rigScenario explicit-leg claude-native "" claude
rigEntry --cli-auto --cli claude
rigAssert "the bash console opens"                          "$( rigBashConsole )" yes
rigAssert "the root harness is not called"                  "$( rigRootCalls )" 0
rigAssert "no vendor binary is started"                     "$( rigStarted claude )" 0
rigAssert "it says --cli chose the leg"                     "$( rigHolds "$rigDir/err" 'chosen by --cli' )" yes
echo "-- sibling of that refusal: --cli names the vendor CLI --"
rigEntry --cli-auto --cli claude-native
rigAssert "the vendor claude is started"                    "$( rigStarted claude )" 1

echo "-- an explicit --cli on an interactive start is honoured over --cli-auto and the setting --"
rigScenario explicit-cli claude "" claude copilot
rigEntry --cli-auto --cli copilot-native
rigAssert "the named copilot-native is started"             "$( rigStarted copilot )" 1
rigAssert "the configured claude leg is not run"            "$( rigStarted claude )" 0
rigAssert "the root harness is not called"                  "$( rigRootCalls )" 0

echo "-- a spawn is unchanged: --non-interactive with the leg configured --"
rigScenario spawn-claude claude "" claude
rigEntry --cli-configured --non-interactive RIG-PROMPT
rigAssert "the leg is selected by name"                     "$( rigHolds "$rigDir/out" 'DISTRO_CONSOLE_EXEC=claude' )" yes
rigAssert "no vendor binary is started"                     "$( rigStarted claude )" 0
rigAssert "the root harness is not called"                  "$( rigRootCalls )" 0

if [ "$rigFailCount" -ne 0 ] ; then
	echo "⛔ CONSOLE INTERACTIVE ENTRY CHECK FAILED: $rigFailCount of $(( rigPassCount + rigFailCount )) assertion(s)" >&2 ; exit 1
fi
printf 'CONSOLE_INTERACTIVE_ENTRY: OK (%d assertions, offline, rig tree only)\n' "$rigPassCount"
